# Site settings
title: Fan Yang
email: fanyangxyz33@gmail.com
description: "machine learning and generative art"
baseurl: ""
url: "http://fanyangxyz.github.io"
github_username: fanyangxyz

# Build settings
markdown: kramdown
permalink: /:title/

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
